### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Lulalaby**

### CODE REVIEW

**Comment by appinteractive** [comment]
Sorry @Lulalaby what are you doing?

**Comment by roschaefer** [comment]
@appinteractive apparently she merged `kubernetes`<-`master`.

@Lulalaby we have our own deployment repository now: [Nitro-Deployment](/Human-Connection/Nitro-Deployment)

**Comment by appinteractive** [comment]
So the branch can be killed!?

**Comment by Lulalaby** [comment]
yeah

**Comment by roschaefer** [comment]
deleted, yes

**Comment by Lulalaby** [comment]
ok

**Comment by Lulalaby** [comment]
done

**Pull request merged**
