### PR TITLE
[WIP] 37 full text search top bar

### PR DESCRIPTION
**Pull request by appinteractive**
## Preperation 

1. Create an index
```
CALL db.index.fulltext.createNodeIndex("postTitleAndContent",["Post"],["title", "content"])
```

2. find some posts
```
{
  findPosts(filter: "Julian", limit: 10) {
    title
    slug
    createdAt
  }
}
```

## Todo`s

- [x] create index automatically or by command like `db:migrate`
- [x] write basic api tests

## Relations
Related with https://github.com/Human-Connection/Nitro-Web/pull/177

### CODE REVIEW

**Comment by appinteractive** [comment]
In the future I would like to have an api like that:
```
search(filter: "Julian", limit: 10) {
  posts {
    title
  }
  users {
    name
  }
}
```

**Comment by appinteractive** [comment]
Related article: https://blog.grandstack.io/using-neo4js-full-text-search-with-graphql-e3fa484de2ea

**Comment by roschaefer** [comment]
Cool, I'm working on it. If sb. wants to pair, just ask.

@appinteractive I just tried out these steps. Works as expected. Does it scale?

**Comment by appinteractive** [comment]
What do you mean with scale? We will see how the performance will be, at least it’s an indexed search so the db should handle it. When we will need better performance we can then extend it, for now it should be enough.

**Comment by roschaefer** [comment]
@appinteractive running it twice does not do anything. You can repeat the procedure with:
```
docker-compose down -v
docker-compose up --build
```
I would not add code comments but suggest some documentation in https://docs.human-connection.org/nitro instead.

**Comment by Tirokk** [comment]
@roschaefer I pulled this branch onto my local machine, but just don’t understand how to create the index …
… so that I can find some posts with GraphQL like it is described at the top of this page.

**Comment by Tirokk** [comment]
Okay, sorry!!!
Now I got it ! 👍🏼

**Comment by appinteractive** [comment]
@roschaefer @Tirokk @mattwr18 this could be merged for now, what you thing?

**Comment by mattwr18** [comment]
I think so, it wouldn't affect anything if we merged the back end independent of the front end, or would it?
Although, I am really keen to get the front end merged as well

**Comment by appinteractive** [comment]
So then give a thumbs up 👍

**Pull request merged**
