### PR TITLE
Docker ignore scripts folder, bash compatibility

### PR DESCRIPTION
**Pull request by roschaefer**
For full stack testing.

### CODE REVIEW

**Comment by roschaefer** [comment]
@appinteractive excellent, here is the first automatically triggered build of this repository: https://travis-ci.com/Human-Connection/Human-Connection/builds/94220253

**Comment by appinteractive** [comment]
@roschaefer this pull-request can be rejected now after we trigger the integration tests from the web repo directly now?

**Comment by roschaefer** [comment]
@appinteractive I updated the title, yes, most of the code is obsolete.

**Comment by roschaefer** [comment]
@appinteractive I'll merge the rest of it

**Pull request merged**
